apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::157851817616:role/eksctl-genaieks-nodegroup-EKSgena-NodeInstanceRole-EGN4QLLNTN38
